# Generated by Django 3.2.4 on 2021-07-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ques_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
