# Generated by Django 3.2.4 on 2021-07-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_ques_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='response_ans',
        ),
    ]
